name: Run GBP

on:
  push:
    branches:
      # - master

jobs:
  run-gbp:
    runs-on: ubuntu-20.04

    steps:
      - name: Test
        uses: docker://registry.salsa.debian.org/salsa-ci-team/pipeline/gbp:latest
        with:
          entrypoint: /bin/sh
          args: "-c \"echo Hi; ls -la\""
