name: Run GBP

on:
  push:
    branches:
      # - master

jobs:
  run-gbp:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: source_dir

      - name: Get Time
        id: get-time
        run: |
          echo "::set-output name=datetime::$(/bin/date --iso-8601=seconds)"
        shell: bash

      - uses: actions/cache@v2
        with:
          path: .ccache
          key: ${{ runner.os }}-ccache-${{ steps.get-time.outputs.datetime }}
          restore-keys: |
            ${{ runner.os }}-ccache-

      - name: Build Package
        uses: docker://registry.salsa.debian.org/salsa-ci-team/pipeline/gbp:latest
        with:
          entrypoint: /bin/sh
          args: source_dir/.scripts/buildpkg.sh

