name: Packaging

on:
  push

env:
  RELEASE: unstable
  PROJECT_NAME: cros3

jobs:
  build-package:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: source_dir

      - name: Get Time
        id: get-time
        run: |
          echo "::set-output name=datetime::$(/bin/date --iso-8601=seconds)"
        shell: bash

      - uses: actions/cache@v2
        with:
          path: .ccache
          key: ${{ runner.os }}-${{ env.RELEASE }}-ccache-${{ steps.get-time.outputs.datetime }}
          restore-keys: |
            ${{ runner.os }}-${{ env.RELEASE }}-ccache-

      #- name: Run gbp
      #  uses: docker://registry.salsa.debian.org/salsa-ci-team/pipeline/gbp:latest
      #  with:
      #    entrypoint: /bin/bash
      #    args: source_dir/.scripts/rungbp.sh

      - name: Build Package
        uses: docker://registry.salsa.debian.org/salsa-ci-team/pipeline/gbp:latest
        with:
          entrypoint: /bin/bash
          args: source_dir/.scripts/buildpkg.sh

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-${{ env.RELEASE }}-debpkg
          path: debian/output/*
          retention-days: 2

  run-lintian:
    needs: [ build-package ]
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: source_dir

      - name: Download all Debian packaging workflow run artifacts
        uses: actions/download-artifact@v2

      - name: Run Lintian on ${{ env.RELEASE }}
        uses: docker://registry.salsa.debian.org/salsa-ci-team/pipeline/lintian:testing
        with:
          entrypoint: /bin/bash
          args: source_dir/.scripts/runlintian.sh

      - name: Publish Lintian Results
        uses: EnricoMi/publish-unit-test-result-action@v1.7
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: lintian/*.xml
          report_individual_runs: true

      - name: Upload Lintian results
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: ${{ runner.os }}-${{ env.RELEASE }}-lintian
          path: lintian
          retention-days: 2

  test-dkms:
    needs: [ build-package ]
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        container: 
          - "debian:stable"
          - "debian:bullseye"
          - "debian:unstable"
          - "debian:testing"

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: source_dir

      - name: Download all Debian packaging workflow run artifacts
        uses: actions/download-artifact@v2

      - name: Install package and compile on ${{ matrix.container }}
        run: ./source_dir/.scripts/testdkms.sh

  create-aptly-repo:
    needs: [ build-package ]
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: source_dir

      - name: Download all Debian packaging workflow run artifacts
        uses: actions/download-artifact@v2

      - name: Prepare aptly repo
        uses: docker://registry.salsa.debian.org/salsa-ci-team/pipeline/aptly
        with:
          entrypoint: /bin/bash
          args: source_dir/.scripts/prepaptly.sh

      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
          name: ${{ runner.os }}-${{ env.RELEASE }}-repo
          path: debrepo.tar.gz
          retention-days: 2

  build-rpm:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        container: 
          - "centos:7"
          - "centos:8"

    container:
      image: ${{ matrix.container }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: source_dir

      - name: Build RPM on ${{ matrix.container }}
        run: ./source_dir/.scripts/buildrpm.sh

  deploy-repos-and-data:
    needs: [ run-lintian, create-aptly-repo ]
    runs-on: ubuntu-20.04

    steps:
      - name: Download all Debian packaging workflow run artifacts
        uses: actions/download-artifact@v2

      - name: Filter out repo data
        run: |
          mkdir -p publish/apt
          for TAR in *-repo/*.tar.*; do tar xf $TAR -C publish/apt/; done

      - name: Filter out Lintian HTML
        run: |
          mkdir -p publish/lintian
          echo '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">' > publish/lintian/index.html
          echo '<html><body>' >> publish/lintian/index.html
          for LINTIAN_DIR in *-lintian; do
            mv ${LINTIAN_DIR} publish/lintian/;
            LINTIAN_HTML=$(ls -1 ${LINTIAN_DIR}/*.html)
            echo "<a href=\"${LINTIAN_HTML}\">${LINTIAN_HTML}</a><br />" >> publish/lintian/index.html
          done
          echo '</body></html>' >> publish/lintian/index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        #if: endsWith(github.event.ref, '/master')
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./publish
          force_orphan: true
